# fly.toml app configuration file generated for hidek-xyz on 2023-11-15T14:19:15-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hidek-xyz"
primary_region = "iad"
kill_signal = "SIGTERM"
swap_size_mb = 512

[build]

# sqlite does not have migration bin
#[deploy]
#  release_command = "/app/bin/migrate"

# mounts hidek_xyz volume into filesystem (/data/hidek_xyz)
[mounts]
  source = "hidek_xyz"
  destination = "/data"

[env]
  DATABASE_PATH = "/data/hidek_xyz/hidek_xyz.db" # system will create/read from this file
  PHX_HOST = "hidek.xyz"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
